// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: kubernetes.proto

package go_micro_srv_kubernetes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Kubernetes service

type KubernetesService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Kubernetes_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Kubernetes_PingPongService, error)
}

type kubernetesService struct {
	c    client.Client
	name string
}

func NewKubernetesService(name string, c client.Client) KubernetesService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.kubernetes"
	}
	return &kubernetesService{
		c:    c,
		name: name,
	}
}

func (c *kubernetesService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Kubernetes.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubernetesService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Kubernetes_StreamService, error) {
	req := c.c.NewRequest(c.name, "Kubernetes.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &kubernetesServiceStream{stream}, nil
}

type Kubernetes_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type kubernetesServiceStream struct {
	stream client.Stream
}

func (x *kubernetesServiceStream) Close() error {
	return x.stream.Close()
}

func (x *kubernetesServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *kubernetesServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *kubernetesServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kubernetesService) PingPong(ctx context.Context, opts ...client.CallOption) (Kubernetes_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Kubernetes.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &kubernetesServicePingPong{stream}, nil
}

type Kubernetes_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type kubernetesServicePingPong struct {
	stream client.Stream
}

func (x *kubernetesServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *kubernetesServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *kubernetesServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *kubernetesServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *kubernetesServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Kubernetes service

type KubernetesHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Kubernetes_StreamStream) error
	PingPong(context.Context, Kubernetes_PingPongStream) error
}

func RegisterKubernetesHandler(s server.Server, hdlr KubernetesHandler, opts ...server.HandlerOption) error {
	type kubernetes interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Kubernetes struct {
		kubernetes
	}
	h := &kubernetesHandler{hdlr}
	return s.Handle(s.NewHandler(&Kubernetes{h}, opts...))
}

type kubernetesHandler struct {
	KubernetesHandler
}

func (h *kubernetesHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.KubernetesHandler.Call(ctx, in, out)
}

func (h *kubernetesHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.KubernetesHandler.Stream(ctx, m, &kubernetesStreamStream{stream})
}

type Kubernetes_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type kubernetesStreamStream struct {
	stream server.Stream
}

func (x *kubernetesStreamStream) Close() error {
	return x.stream.Close()
}

func (x *kubernetesStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *kubernetesStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *kubernetesStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *kubernetesHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.KubernetesHandler.PingPong(ctx, &kubernetesPingPongStream{stream})
}

type Kubernetes_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type kubernetesPingPongStream struct {
	stream server.Stream
}

func (x *kubernetesPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *kubernetesPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *kubernetesPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *kubernetesPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *kubernetesPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
