// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: kubernetes.proto

package go_micro_srv_kubernetes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Kubernetes service

type KubernetesService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	PodGet(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type kubernetesService struct {
	c    client.Client
	name string
}

func NewKubernetesService(name string, c client.Client) KubernetesService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.kubernetes"
	}
	return &kubernetesService{
		c:    c,
		name: name,
	}
}

func (c *kubernetesService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Kubernetes.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubernetesService) PodGet(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Kubernetes.PodGet", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Kubernetes service

type KubernetesHandler interface {
	Call(context.Context, *Request, *Response) error
	PodGet(context.Context, *Request, *Response) error
}

func RegisterKubernetesHandler(s server.Server, hdlr KubernetesHandler, opts ...server.HandlerOption) error {
	type kubernetes interface {
		Call(ctx context.Context, in *Request, out *Response) error
		PodGet(ctx context.Context, in *Request, out *Response) error
	}
	type Kubernetes struct {
		kubernetes
	}
	h := &kubernetesHandler{hdlr}
	return s.Handle(s.NewHandler(&Kubernetes{h}, opts...))
}

type kubernetesHandler struct {
	KubernetesHandler
}

func (h *kubernetesHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.KubernetesHandler.Call(ctx, in, out)
}

func (h *kubernetesHandler) PodGet(ctx context.Context, in *Request, out *Response) error {
	return h.KubernetesHandler.PodGet(ctx, in, out)
}
